apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
resources:
  - RHEL-9_2-VM_deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: vm-count
    literals:
      - vmCount=10

patchesStrategicMerge:
  - |-
    apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      name: my-vm-0
    spec:
      running: true
      instancetype:
        name: u1.medium
      preference:
        name: rhel.9
      dataVolumeTemplates:
        - metadata:
            name: my-vm-0-volume
          spec:
            sourceRef:
              kind: DataSource
              name: rhel9
              namespace: openshift-virtualization-os-images
            storage:
              resources:
                requests:
                  storage: '32212254720'
              storageClassName: sc-gold
      template:
        metadata:
          labels:
            network.kubevirt.io/headlessService: headless
        spec:
          domain:
            devices:
              autoattachPodInterface: true
              disks:
              - name: rootdisk
                dataVolume:
                  name: my-vm-0-volume
              - name: cloudinitdisk
                cloudInitNoCloud:
                  userData: |
                    #cloud-config
                    chpasswd:
                      expire: false
                    password: o8af-owof-vxr8
                    user: rhel
          interfaces:
            - name: bridge
              model: virtio
          networks:
            - name: {}
              pod: {}
          volumes:
            - name: rootdisk
              dataVolume:
                name: my-vm-0-volume
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
                  chpasswd:
                    expire: false
                  password: o8af-owof-vxr8
                  user: rhel
          subdomain: headless
