apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: default
spec:
  interval: 10m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: default
  validation: client
