apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-01
  namespace: default
spec:
  running: true
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  dataVolumeTemplates:
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-template
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 4Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: rhel
            chpasswd: { expire: False }
            ssh_pwauth: True

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-02
  namespace: default
spec:
  running: true
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  dataVolumeTemplates:
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-template
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 4Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: rhel
            chpasswd: { expire: False }
            ssh_pwauth: True
