apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
namespace: default
metadata:
  name: vm-pool-rhel9
spec:
  running: true
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  dataVolumeTemplates:
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '32212254720'
          storageClassName: sc-gold
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vmpool: vm-pool-rhel9
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: vm-pool-rhel9
    spec:
      runStrategy: Always
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: vm-pool-rhel9
        spec:
          domain:
            devices:
            autoattachPodInterface: true
              disks:
              - disk:
                  bus: virtio
                name: containerdisk
            resources:
              requests:
                memory: 128Mi
          terminationGracePeriodSeconds: 0
          interfaces:
          - name: default
            bridge:
